package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import javafx.event.ActionEvent;

public class UISolicitudController {
	@FXML
	private Button btnSolicitar;
	@FXML
	private Button btnCerrar;
	@FXML
	private TextField tfDestino;
	@FXML
	private TextField tfOrigen;

	// Event Listener on Button[#btnSolicitar].onAction
	@FXML
	public void solicitar(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void cerrarVentana(ActionEvent event) {
		closeWindows(null);
	}

	public void closeWindows(Object object) {
		try {
			FXMLLoader loader = new FXMLLoader(
				getClass().getResource("/presentation/UIMain.fxml"));
		    Parent root = loader.load();
		    Scene scene = new Scene(root);
		    Stage stage = new Stage();
		    stage.setScene(scene);
		   UIMainController controller = loader.getController(); 
		 
		    
		    stage.show();
		    Stage temp = (Stage)this.btnCerrar.getScene().getWindow();
		    temp.close();
		
		
		}catch(Exception e) {
			e.printStackTrace();
		}
		
	}
}
